import { Era } from './types';

export const ERAS3: Era[] = [
  {
    id:'mongol_timurid',
    label:{ en:'VI · Mongols & Timurids', fa:'شش · مغولان و تیموریان' },
    years:'1219–1506 AD',
    desc:{ en:'The Mongol catastrophe and its cultural aftermath. Genghis Khan\'s invasion erases centuries of civilization across Khorasan; the Ilkhanate then becomes the most lavish patron of Persian art in history. Timur\'s campaigns repeat the destruction — yet the Timurid renaissance at Herat surpasses even that.',
           fa:'فاجعه مغول و پیامد فرهنگی آن. تهاجم چنگیزخان قرن‌ها تمدن در خراسان را نابود می‌کند؛ ایلخانان سپس فداکارترین حامیان هنر فارسی در تاریخ می‌شوند. لشکرکشی‌های تیمور ویرانی را تکرار می‌کند — اما رنسانس تیموری هرات حتی از آن فراتر می‌رود.' },
    snapshots:[
      {
        year:'1290 AD', yearFA:'۱۲۹۰ میلادی',
        title:{ en:'Ilkhanate & Atabegs Under Mongol Shadow', fa:'ایلخانان و اتابکان زیر سایه مغول' },
        powers:[
          { name:{en:'Ilkhanate (Mongol Persia)',fa:'ایلخانان (ایران مغول)'}, culture:'turkic',
            capital:{en:'Maragha / Tabriz / Sultaniyya',fa:'مراغه / تبریز / سلطانیه'}, status:'direct', dates:'1256–1335 AD',
            regions:['mesopotamia','media','elam','fars','khorasan','tabaristan','azerbaijan','caucasus'],
            desc:{en:'Hulagu Khan, grandson of Genghis, destroyed the Abbasid Caliphate in 1258 (ending 500 years of the institution) and founded the Ilkhanate. Under Ghazan Khan (converted to Islam 1295), the Ilkhanate became the greatest patron of Persian manuscript painting, astronomy, and historiography — Rashid al-Din\'s Jami\' al-Tawarikh was written at their court.',
                  fa:'هلاکوخان، نوه چنگیز، خلافت عباسی را در ۱۲۵۸ (پایان ۵۰۰ سال خلافت) نابود کرد و ایلخانات را پایه گذاشت. در دوران غازان خان (اسلام‌آورنده ۱۲۹۵)، ایلخانات بزرگ‌ترین حامی نگارگری، نجوم و تاریخ‌نگاری فارسی شد.'} },
          { name:{en:'Kartid Dynasty (Mongol vassal)',fa:'آل کرت (دست‌نشانده مغول)'}, culture:'persian',
            capital:{en:'Herat',fa:'هرات'}, status:'vassal', dates:'1245–1389 AD',
            regions:['bactria','sistan'],
            desc:{en:'The Kartids of Herat served the Ilkhanate as loyal vassals while preserving Persian administration and culture in eastern Khorasan. Their loyalty was rewarded with growing autonomy as the Ilkhanate weakened.',
                  fa:'کرتیان هرات به عنوان دست‌نشانده وفادار ایلخانان خدمت کردند و در عین حال اداره و فرهنگ فارسی را در خراسان شرقی حفظ کردند.'} },
          { name:{en:'Salghurid / Injuid Fars',fa:'سلغریان / اینجوییان فارس'}, culture:'persian',
            capital:{en:'Shiraz',fa:'شیراز'}, status:'vassal', dates:'1148–1357 AD',
            regions:['fars'],
            desc:{en:'The Salghurid Atabegs submitted to the Mongols in 1262, becoming Ilkhanate vassals. Their successors the Injuids (1335–57) ruled Fars after Ilkhanate collapse — and it was under the Injuid court that the poet Hafez of Shiraz composed his first ghazals.',
                  fa:'اتابکان سلغری در ۱۲۶۲ تسلیم مغولان شدند. جانشینانشان اینجوییان (۱۳۳۵-۱۳۵۷) پس از فروپاشی ایلخانان بر فارس فرمان راندند — و در همین دربار بود که حافظ شیرازی نخستین غزل‌هایش را سرود.'} },
          { name:{en:'Eldiguzid / Ilkhanate Azerbaijan',fa:'الدگزی / آذربایجان ایلخانی'}, culture:'turkic',
            capital:{en:'Tabriz',fa:'تبریز'}, status:'direct', dates:'c.1256–1335 AD',
            regions:['azerbaijan'],
            desc:{en:'Tabriz became the Ilkhanate\'s main capital under Arghun Khan, hosting the world\'s first international art market and diplomatic hub between the Mongol courts, Europe, and China.',
                  fa:'تبریز در دوران ارغون خان به پایتخت اصلی ایلخانان تبدیل شد و نخستین بازار هنری بین‌المللی جهان و مرکز دیپلماتیک میان دربارهای مغول، اروپا و چین بود.'} },
          { name:{en:'Khwarazmian Remnants / Chagatai',fa:'بازماندگان خوارزمشاهی / چغتایی'}, culture:'turkic',
            capital:{en:'Samarkand',fa:'سمرقند'}, status:'contested', dates:'c.1226–1370 AD',
            regions:['transoxiana'],
            desc:{en:'After the Mongols destroyed Khwarezm, the Chagatai Khanate held Transoxiana. This region was the most contested zone of Mongol succession — eventually producing Timur, who was born near Samarkand in 1336.',
                  fa:'پس از نابودی خوارزم توسط مغولان، خانات چغتایی فرارود را نگه داشت. این منطقه اصلی‌ترین ناحیه رقابت جانشینی مغول بود — و سرانجام تیمور را که در ۱۳۳۶ نزدیک سمرقند زاده شد پدید آورد.'} },
          { name:{en:'Anatolia — Seljuks of Rum / Karamanids',fa:'آناتولی — سلجوقیان روم / قرمانیان'}, culture:'turkic',
            capital:{en:'Konya / Karaman',fa:'قونیه / قرمان'}, status:'contested', dates:'c.1077–1475 AD',
            regions:['anatolia'],
            desc:{en:'The Seljuks of Rum (Anatolia) maintained a sophisticated Persian-cultured sultanate at Konya until Mongol suzerainty. Rumi composed the Masnavi at their court. After Mongol devastation, the Karamanids and other beyliks fragmented Anatolia.',
                  fa:'سلجوقیان روم (آناتولی) سلطنتی ایرانی‌فرهنگ در قونیه داشتند تا دوران تبعیت مغولی. مولانا مثنوی را در همین دربار سرود. پس از ضربات مغول، قرمانیان و بیگ‌نشین‌های دیگر آناتولی را تکه‌پاره کردند.'} },
        ]
      },
      {
        year:'1340 AD', yearFA:'۱۳۴۰ میلادی',
        title:{ en:'Post-Ilkhanate Anarchy', fa:'هرج و مرج پس از ایلخانان' },
        powers:[
          { name:{en:'Jalayirid Sultanate',fa:'سلطنت جلایری'}, culture:'turkic',
            capital:{en:'Baghdad / Tabriz',fa:'بغداد / تبریز'}, status:'direct', dates:'1335–1432 AD',
            regions:['mesopotamia','azerbaijan'],
            desc:{en:'Mongol Ilkhanate successors in Iraq and Azerbaijan. Their court produced the Demotte Shahnameh and other masterworks of Persian miniature painting. Constantly pressured by the Black Sheep and White Sheep Turkmen.',
                  fa:'جانشینان ایلخانی مغول در عراق و آذربایجان. دربارشان شاهنامه دموت و دیگر شاهکارهای نگارگری فارسی را پدید آورد. دائماً در فشار ترکمانان قره‌قویونلو و آق‌قویونلو بود.'} },
          { name:{en:'Muzaffarid Dynasty',fa:'آل مظفر'}, culture:'persian',
            capital:{en:'Yazd / Shiraz / Isfahan',fa:'یزد / شیراز / اصفهان'}, status:'direct', dates:'1314–1393 AD',
            regions:['fars','media','elam'],
            desc:{en:'Expanded from Yazd to control much of southern and central Iran. Hafez of Shiraz flourished under Muzaffarid patronage. Timur executed the entire dynasty in 1393.',
                  fa:'از یزد گسترش یافت و بخش بزرگی از جنوب و مرکز ایران را کنترل کرد. حافظ شیراز در دوران آل مظفر شکوفا شد. تیمور در ۱۳۹۳ تمام خاندان را اعدام کرد.'} },
          { name:{en:'Sarbadar Republic',fa:'جمهوری سربداران'}, culture:'persian',
            capital:{en:'Sabzevar',fa:'سبزوار'}, status:'direct', dates:'1337–1376 AD',
            regions:['khorasan','tabaristan'],
            desc:{en:'A unique Shi\'a revolutionary state. Started as a peasant anti-Mongol rebellion, became a recognized regional power. The young Timur incorporated their last ruler Khwaja Ali Mu\'ayyad peacefully.',
                  fa:'دولت انقلابی شیعه منحصربه‌فرد. از شورش دهقانان ضد مغول آغاز شد و به قدرتی شناخته‌شده تبدیل گشت. تیمور جوان آخرین حاکمشان خواجه علی مؤید را آرام در خود ادغام کرد.'} },
          { name:{en:'Kartid Dynasty',fa:'آل کرت'}, culture:'persian',
            capital:{en:'Herat',fa:'هرات'}, status:'direct', dates:'1245–1389 AD',
            regions:['bactria','sistan'],
            desc:{en:'Mongol vassals who evolved into independent rulers. Herat under Kartid rule was a cultural beacon before Timur destroyed the dynasty in 1389.',
                  fa:'دست‌نشانده مغولی که به حاکمان مستقل تبدیل شدند. هرات زیر آل کرت چراغ فرهنگی بود تا اینکه تیمور در ۱۳۸۹ سلسله را برانداخت.'} },
          { name:{en:'Chagatai / Moghulistan',fa:'چغتایی / مغولستان'}, culture:'turkic',
            capital:{en:'Samarkand',fa:'سمرقند'}, status:'direct', dates:'1226–1370 AD',
            regions:['transoxiana'],
            desc:{en:'Chagatai descendants held Transoxiana, endlessly split between sedentary Persian-cultured factions and eastern nomadic clans. Timur seized Samarkand from the last Chagatai ruler in 1370.',
                  fa:'فرزندان جغتای فرارود را نگه داشتند، مدام میان جناح‌های یکجانشین ایرانی‌فرهنگ و کوچ‌نشینان شرقی شکاف می‌خوردند. تیمور در ۱۳۷۰ سمرقند را از آخرین حاکم چغتایی گرفت.'} },
          { name:{en:'Chobanid / Black Sheep Turkmen (rising)',fa:'چوپانیان / قره‌قویونلو (در حال قدرت‌گیری)'}, culture:'turkic',
            capital:{en:'Tabriz',fa:'تبریز'}, status:'contested', dates:'1335–1468 AD',
            regions:['caucasus'],
            desc:{en:'The Chobanids briefly held Azerbaijan after the Ilkhanate collapse. They were succeeded and absorbed by the Black Sheep Turkmen (Qara Qoyunlu), who would dominate Azerbaijan and western Iran before Timurid pressure.',
                  fa:'چوپانیان پس از فروپاشی ایلخانان به‌طور موقت آذربایجان را نگه داشتند. قره‌قویونلو جانشین و جذب‌کننده آنان شد و پیش از فشار تیموری بر آذربایجان و غرب ایران فرمان راند.'} },
        ]
      },
      {
        year:'1450 AD', yearFA:'۱۴۵۰ میلادی',
        title:{ en:'Timurid Renaissance & Successor Dynasties', fa:'رنسانس تیموری و سلسله‌های جانشین' },
        powers:[
          { name:{en:'Timurid Empire',fa:'امپراتوری تیموری'}, culture:'persian',
            capital:{en:'Samarkand / Herat',fa:'سمرقند / هرات'}, status:'direct', dates:'1370–1507 AD',
            regions:['khorasan','bactria','sistan','transoxiana'],
            desc:{en:'Timur\'s heirs created the most spectacular Persian cultural renaissance ever known. Shah Rukh ruled from Herat; his son Ulugh Beg built the most accurate observatory of the pre-telescope world in Samarkand. The Timurid style defined Islamic architecture and manuscript illustration for two centuries. Babur, last Timurid, fled to found the Mughal Empire.',
                  fa:'وارثان تیمور باشکوه‌ترین رنسانس فرهنگ فارسی را پدید آوردند. شاهرخ از هرات فرمان راند؛ پسرش الغ‌بیگ دقیق‌ترین رصدخانه پیش از تلسکوپ را در سمرقند ساخت. سبک تیموری برای دو سده معماری و نگارگری اسلامی را تعریف کرد. بابر، آخرین تیموری، گریخت و امپراتوری گورکانی را پایه گذاشت.'} },
          { name:{en:'Black Sheep Turkmen (Qara Qoyunlu)',fa:'قره‌قویونلو'}, culture:'turkic',
            capital:{en:'Tabriz',fa:'تبریز'}, status:'direct', dates:'1374–1468 AD',
            regions:['azerbaijan','mesopotamia','media'],
            desc:{en:'The Qara Qoyunlu ("Black Sheep") Turkmen confederation held Azerbaijan and Iraq after briefly defeating the Jalayirids. At their height under Jahan Shah, they controlled territory from Baghdad to Khorasan\'s borders.',
                  fa:'ترکمانان قره‌قویونلو پس از شکست موقت جلایریان، آذربایجان و عراق را نگه داشتند. در اوج قدرتشان زیر جهانشاه از بغداد تا مرزهای خراسان را کنترل می‌کرد.'} },
          { name:{en:'White Sheep Turkmen (Aq Qoyunlu)',fa:'آق‌قویونلو'}, culture:'turkic',
            capital:{en:'Diyarbakır / Tabriz',fa:'دیاربکر / تبریز'}, status:'direct', dates:'1378–1508 AD',
            regions:['anatolia','caucasus','fars','elam'],
            desc:{en:'The Aq Qoyunlu ("White Sheep") defeated the Black Sheep in 1468, creating a major confederation from Anatolia to Fars under Uzun Hasan. Their defeat of the Timurids in Khorasan was halted; Venice sought them as anti-Ottoman allies.',
                  fa:'آق‌قویونلو در ۱۴۶۸ قره‌قویونلو را شکست داد و از آناتولی تا فارس اتحادیه بزرگی زیر اوزون حسن پدید آورد. ونیز آنان را به عنوان متحد ضد عثمانی می‌جست.'} },
          { name:{en:'Timurid Khorasan / Tabaristan',fa:'خراسان تیموری / طبرستان'}, culture:'persian',
            capital:{en:'Mashhad / Astarabad',fa:'مشهد / استرآباد'}, status:'vassal', dates:'c.1450',
            regions:['tabaristan'],
            desc:{en:'The Caspian littoral and southern Khorasan were controlled by Timurid princes and their local allies — including the Bavandid dynasty, which still clung to its ancient Alborz strongholds.',
                  fa:'کرانه خزر و خراسان جنوبی در دست شاهزادگان تیموری و متحدان محلی‌شان بود — از جمله باوندیان که هنوز به دژهای دیرین البرز چنگ می‌زدند.'} },
        ]
      }
    ]
  }
];
