import { Era } from './types';

export const ERAS2: Era[] = [
  {
    id:'intermezzo',
    label:{ en:'IV · Iranian Intermezzo', fa:'چهار · میانه ایرانی' },
    years:'820–1055 AD',
    desc:{ en:'The densest overlap on the map. As the Abbasid Caliphate fractures, local Iranian Muslim dynasties rise simultaneously — Tahirids, Saffarids, Samanids, Buyids, Ziyarids — alongside mountain enclaves like the Bavandids that outlasted every empire.',
           fa:'متراکم‌ترین تداخل قدرت‌ها در نقشه. خلافت عباسی درهم می‌شکند و سلسله‌های ایرانی مسلمان — طاهریان، صفاریان، سامانی، آل بویه، زیاری — همزمان ظهور می‌کنند.' },
    snapshots:[
      {
        year:'870 AD', yearFA:'۸۷۰ میلادی',
        title:{ en:'Rise of the Saffarids & Tahirid Decline', fa:'برآمدن صفاریان و افول طاهریان' },
        powers:[
          { name:{en:'Saffarid Emirate',fa:'امارت صفاریان'}, culture:'persian',
            capital:{en:'Zaranj',fa:'زرنج'}, status:'direct', dates:'861–1003 AD',
            regions:['sistan','khorasan','fars','bactria'],
            desc:{en:'Founded by Ya\'qub ibn al-Layth al-Saffar, a coppersmith turned warlord. He conquered vast territories from the Tahirids and marched on Baghdad, championing Persian language and local independence.',
                  fa:'توسط یعقوب لیث صفاری، رویگری که به جنگاوری رسید، بنیان نهاده شد. او سرزمین‌های وسیعی را از طاهریان گرفت و به سوی بغداد لشکر کشید و حامی زبان فارسی و استقلال محلی بود.'} },
          { name:{en:'Tahirid Emirate',fa:'امارت طاهریان'}, culture:'persian',
            capital:{en:'Nishapur',fa:'نیشابور'}, status:'vassal', dates:'821–873 AD',
            regions:['transoxiana','tabaristan'],
            desc:{en:'The first semi-independent Iranian dynasty after the Arab conquest. Nominally loyal to the Abbasids, they ruled Khorasan until their capital Nishapur fell to the Saffarids in 873.',
                  fa:'نخستین سلسله نیمه‌مستقل ایرانی پس از فتح اعراب. آنان که در ظاهر وفادار به عباسیان بودند، بر خراسان فرمان راندند تا اینکه پایتختشان نیشابور در ۸۷۳ به دست صفاریان افتاد.'} },
          { name:{en:'Abbasid Caliphate',fa:'خلافت عباسی'}, culture:'arab',
            capital:{en:'Baghdad / Samarra',fa:'بغداد / سامرا'}, status:'direct', dates:'750–1258 AD',
            regions:['mesopotamia','elam','media','azerbaijan','caucasus','anatolia'],
            desc:{en:'Still a formidable power, though beginning to fracture. The Caliphate relied heavily on Turkic slave-soldiers (Ghilman) and faced numerous rebellions, including the Zanj and the Saffarid advance.',
                  fa:'هنوز قدرتی چشمگیر بود، هرچند در حال فروپاشی می‌نمود. خلافت به‌شدت به سربازان برده ترک (غلمان) وابسته بود و با شورش‌های متعددی از جمله زنگیان و پیشروی صفاریان روبه‌رو شد.'} },
          { name:{en:'Bavandid Dynasty',fa:'باوندیان'}, culture:'persian',
            capital:{en:'Amol',fa:'آمل'}, status:'vassal', dates:'665–1598 AD',
            regions:['tabaristan'],
            desc:{en:'A resilient mountain dynasty with Sasanian roots that maintained local autonomy in the Alborz highlands, often resisting direct Islamic or caliphal control in this early period.',
                  fa:'سلسله‌ای کوهستانی و مقاوم با ریشه‌های ساسانی که خودمختاری محلی را در ارتفاعات البرز حفظ کرد و در این دوره اولیه اغلب در برابر کنترل مستقیم اسلامی یا خلافت مقاومت می‌کرد.'} }
        ]
      },
      {
        year:'950 AD', yearFA:'۹۵۰ میلادی',
        title:{ en:'The Great Fragmentation', fa:'پراکندگی بزرگ' },
        powers:[
          { name:{en:'Buyid Dynasty',fa:'آل بویه'}, culture:'persian',
            capital:{en:'Shiraz / Ray / Baghdad',fa:'شیراز / ری / بغداد'}, status:'direct', dates:'934–1055 AD',
            regions:['media','elam','mesopotamia','fars'],
            desc:{en:'The Shi\'a Buyid Daylamite amirs held the Abbasid Caliph in Baghdad as a gilded prisoner while actually governing the empire. Three brothers ruled Fars, Jibal/Media, and Iraq simultaneously — the apogee of Iranian revival.',
                  fa:'امرای دیلمی آل بویه شیعه، خلیفه عباسی بغداد را در قفسی طلایی نگه داشتند و خود امپراتوری را اداره می‌کردند. سه برادر هم‌زمان بر فارس، جبال و عراق فرمان راندند.'} },
          { name:{en:'Samanid Empire',fa:'امپراتوری سامانی'}, culture:'persian',
            capital:{en:'Bukhara',fa:'بخارا'}, status:'direct', dates:'819–999 AD',
            regions:['khorasan','transoxiana'],
            desc:{en:'The most brilliant dynasty of the Iranian renaissance. Their court in Bukhara produced Avicenna and Rudaki, and standardized New Persian (Dari) as a literary language — the foundation of all classical Persian literature.',
                  fa:'درخشان‌ترین سلسله رنسانس ایرانی. دربار بخارا خاستگاه ابن‌سینا و رودکی بود و زبان فارسی دری را به‌عنوان زبان ادبی استانداردسازی کرد.'} },
          { name:{en:'Ziyarid Dynasty',fa:'آل زیار'}, culture:'persian',
            capital:{en:'Gorgan / Amul',fa:'گرگان / آمل'}, status:'direct', dates:'928–1090 AD',
            regions:['tabaristan'],
            desc:{en:'Mardavij ibn Ziyar dreamed of restoring pre-Islamic Persian kingship, wearing Sasanian royal robes and celebrating Nowruz with fire ceremonies. His dynasty ruled the Caspian coast for a century.',
                  fa:'مرداویج بن زیار آرزو داشت پادشاهی پیش از اسلام را احیا کند، خلعت ساسانی می‌پوشید و نوروز را با آتش جشن می‌گرفت.'} },
          { name:{en:'Bavandid Dynasty',fa:'باوندیان'}, culture:'persian',
            capital:{en:'Amol',fa:'آمل'}, status:'vassal', dates:'665–1598 AD',
            regions:['tabaristan'],
            desc:{en:'Extraordinary: this mountain dynasty with Zoroastrian roots survived for nearly a millennium in the Alborz highlands, acknowledging each successive empire without surrendering true independence.',
                  fa:'شگفت‌آور: این سلسله کوهستانی با ریشه‌های زرتشتی تقریباً هزار سال در البرز پایید و هر امپراتوری را به‌رسمیت می‌شناخت بدون اینکه واقعاً تسلیم شود.'} },
          { name:{en:'Saffarid Remnant',fa:'بازمانده صفاریان'}, culture:'persian',
            capital:{en:'Zaranj',fa:'زرنج'}, status:'contested', dates:'c.900–1003 AD',
            regions:['sistan','bactria'],
            desc:{en:'The Saffarids, founded by the coppersmith-turned-warlord Ya\'qub ibn Layth al-Saffar, were reduced to Sistan but maintained nominal independence — a symbol of Iranian identity against Arabizing forces.',
                  fa:'صفاریان را یعقوب لیث صفار، آهنگری که به سرداری رسید، پایه گذاشت. بازماندگانشان در سیستان نماد هویت ایرانی در برابر فرهنگ عربی‌مآبانه بودند.'} },
          { name:{en:'Abbasid Caliphate (nominal)',fa:'خلافت عباسی (صوری)'}, culture:'arab',
            capital:{en:'Baghdad',fa:'بغداد'}, status:'vassal', dates:'750–1258 AD',
            regions:['mesopotamia'],
            desc:{en:'The Caliph in Baghdad held supreme religious authority but zero military power by 950 AD — a gilded prisoner of the Buyid amirs who collected taxes and commanded armies in his name.',
                  fa:'خلیفه بغداد اقتدار مذهبی داشت اما در ۹۵۰ میلادی هیچ قدرت نظامی‌ای نداشت و در دست امرای بویه گرفتار بود.'} },
          { name:{en:'Hamdanid Emirate',fa:'امارت حمدانی'}, culture:'arab',
            capital:{en:'Aleppo / Mosul',fa:'حلب / موصل'}, status:'direct', dates:'890–1004 AD',
            regions:['anatolia','caucasus'],
            desc:{en:'Arab Shi\'a dynasty controlling northern Syria and upper Mesopotamia, famous for sheltering the poet al-Mutanabbi and resisting Byzantine campaigns under Sayf al-Dawla — celebrated in Arabic poetry.',
                  fa:'امارت عرب شیعه که شمال سوریه و موصل را کنترل می‌کرد؛ سیف‌الدوله حمدانی میزبان شاعر متنبی بود و در برابر بیزانس پایداری کرد.'} },
          { name:{en:'Shaddadid Dynasty',fa:'شداداغیل'}, culture:'persian',
            capital:{en:'Dvin (Dvinsk)',fa:'دوین'}, status:'direct', dates:'951–1174 AD',
            regions:['azerbaijan'],
            desc:{en:'A Kurdish Muslim dynasty (Kurds being an Iranian people) ruling parts of Armenia and Arran (northern Azerbaijan), wedged between Byzantine, Georgian Bagratid, and Buyid power.',
                  fa:'سلسله‌ای کرد مسلمان (کردها مردمی ایرانی‌اند) که بخش‌هایی از ارمنستان و اران (آذربایجان شمالی) را میان بیزانس، گرجستان و آل بویه اداره می‌کرد.'} },
        ]
      }
    ]
  },

  {
    id:'ghaznavid_seljuk',
    label:{ en:'V · Ghaznavids & Seljuks', fa:'پنج · غزنویان و سلجوقیان' },
    years:'977–1220 AD',
    desc:{ en:'Two Turkic dynasties transform the Iranian world. The Ghaznavids build a court of Persian literary brilliance at Ghazni; the Great Seljuks then sweep the entire plateau in one generation, creating the largest empire since the Sasanians. Later, the Khwarazmians and Ghurids dominate before the Mongol storm.',
           fa:'دو سلسله ترک جهان ایرانی را دگرگون می‌کنند. غزنویان دربار درخشانی به زبان فارسی در غزنی می‌سازند؛ سلجوقیان بزرگ سپس یک نسله تمام فلات را درمی‌نوردند. سپس خوارزمشاهیان و غوریان پیش از طوفان مغول چیرگی می‌یابند.' },
    snapshots:[
      {
        year:'1030 AD', yearFA:'۱۰۳۰ میلادی',
        title:{ en:'Ghaznavid Apogee — Mahmud\'s Court', fa:'اوج غزنویان — دربار محمود' },
        powers:[
          { name:{en:'Ghaznavid Empire',fa:'امپراتوری غزنوی'}, culture:'turkic',
            capital:{en:'Ghazni',fa:'غزنی'}, status:'direct', dates:'977–1186 AD',
            regions:['khorasan','bactria','sistan','transoxiana'],
            desc:{en:'Sultan Mahmud of Ghazni made 17 raids into India, funded a magnificent Persian court, and patronized Ferdowsi (Shahnameh), al-Biruni, and Unsuri. The Ghaznavids were Turkic slave-soldiers who became the greatest patrons of Persian culture of their age.',
                  fa:'سلطان محمود غزنوی ۱۷ بار به هند تاخت، دربار فارسی باشکوهی پدید آورد و از فردوسی (شاهنامه)، بیرونی و عنصری حمایت کرد. غزنویان سربازان برده ترک بودند که بزرگ‌ترین حامیان فرهنگ فارسی شدند.'} },
          { name:{en:'Buyid Dynasty (late)',fa:'آل بویه (متأخر)'}, culture:'persian',
            capital:{en:'Shiraz / Ray',fa:'شیراز / ری'}, status:'direct', dates:'934–1055 AD',
            regions:['media','elam','mesopotamia','fars'],
            desc:{en:'The Buyids were in their final decades, still holding Baghdad and the Abbasid Caliph captive, but weakened by succession disputes. The Seljuk advance would end their rule within a generation.',
                  fa:'آل بویه در دهه‌های پایانی خود بودند، هنوز بغداد و خلیفه را در دست داشتند اما در اثر جنگ‌های جانشینی ضعیف شده بودند. پیشروی سلجوقیان در یک نسله به فرمانروایی‌شان پایان داد.'} },
          { name:{en:'Samanid Remnants / Qarakhanids',fa:'بازماندگان سامانیان / قراخانیان'}, culture:'turkic',
            capital:{en:'Samarkand',fa:'سمرقند'}, status:'contested', dates:'999–1212 AD',
            regions:['transoxiana','caucasus'],
            desc:{en:'After the Samanids fell in 999 AD (jointly to Ghaznavids and Qarakhanids), the Qarakhanid Khanate took Transoxiana. These Turkic Muslims were early adopters of Persian literary culture — their courts wrote poetry in both Turkic and Persian.',
                  fa:'پس از سقوط سامانیان در ۹۹۹ میلادی (به دست غزنویان و قراخانیان)، قراخانیان فرارود را گرفتند. این مسلمانان ترک از نخستین پذیرندگان فرهنگ ادبی فارسی بودند.'} },
          { name:{en:'Abbasid Caliphate (Buyid prisoner)',fa:'خلافت عباسی (زندانی بوییان)'}, culture:'arab',
            capital:{en:'Baghdad',fa:'بغداد'}, status:'vassal', dates:'750–1258 AD',
            regions:['mesopotamia'],
            desc:{en:'The Caliph al-Qadir (r.991–1031) was a Buyid prisoner in all but name, yet retained pan-Islamic religious authority. His Sunni proclamations influenced the coming Seljuk legitimation of power.',
                  fa:'خلیفه القادر (۹۹۱-۱۰۳۱) عملاً زندانی بوییان بود، اما اقتدار دینی سرتاسری اسلامی داشت. اعلامیه‌های سنی‌مذهب او بر مشروعیت‌سازی آتی سلجوقیان تأثیر گذاشت.'} },
          { name:{en:'Kakuyid Dynasty',fa:'آل کاکویه'}, culture:'persian',
            capital:{en:'Isfahan',fa:'اصفهان'}, status:'direct', dates:'1008–1051 AD',
            regions:['azerbaijan'],
            desc:{en:'A Daylamite (Iranian highland) dynasty related to the Buyids who carved out a principality centered on Isfahan and Yazd, surviving between Buyid and Ghaznavid competition until the Seljuk tide.',
                  fa:'سلسله‌ای دیلمی (ایرانی کوهستانی) وابسته به بوییان که امارتی با مرکزیت اصفهان و یزد ایجاد کرد و میان رقابت بوییان و غزنویان تا موج سلجوقی دوام آورد.'} },
        ]
      },
      {
        year:'1090 AD', yearFA:'۱۰۹۰ میلادی',
        title:{ en:'Great Seljuk Empire at its Zenith', fa:'امپراتوری سلجوقی بزرگ در اوج' },
        powers:[
          { name:{en:'Great Seljuk Empire',fa:'امپراتوری سلجوقی بزرگ'}, culture:'turkic',
            capital:{en:'Isfahan / Nishapur',fa:'اصفهان / نیشابور'}, status:'direct', dates:'1037–1194 AD',
            regions:['mesopotamia','media','elam','fars','khorasan','tabaristan','azerbaijan','transoxiana'],
            desc:{en:'Tughril, Alp Arslan, and Malik Shah built the largest empire since the Sasanians. They defeated Byzantium at Manzikert (1071), made the Caliph their figurehead, and presided over a golden age of Persian administration, architecture (Isfahan\'s Jameh Mosque), and philosophy (Nizam al-Mulk\'s Siyasatnama). The empire ran on Persian bureaucrats and Turkic soldiers.',
                  fa:'طغرل، آلپ ارسلان و ملکشاه بزرگ‌ترین امپراتوری از روزگار ساسانیان پدید آوردند. بیزانس را در مانزیکرت (۱۰۷۱) شکست دادند، خلیفه را دست‌نشانده خود کردند و دوران طلایی اداره و معماری فارسی را رقم زدند. امپراتوری با دیوانسالاران ایرانی و سربازان ترک اداره می‌شد.'} },
          { name:{en:'Ismaili Nizari State (Assassins)',fa:'دولت نزاری اسماعیلی (فدائیان)'}, culture:'persian',
            capital:{en:'Alamut',fa:'الموت'}, status:'contested', dates:'1090–1256 AD',
            regions:['tabaristan','media'],
            desc:{en:'Hassan-i Sabbah seized the mountain fortress of Alamut in 1090 and built a network of castles across the Alborz and Zagros. His Nizari Ismaili state terrorized Seljuk officials with targeted assassinations — the origin of the word "assassin."',
                  fa:'حسن صباح در ۱۰۹۰ قلعه الموت را گرفت و شبکه‌ای از دژها در البرز و زاگرس ساخت. دولت اسماعیلی نزاری او مقامات سلجوقی را با ترور هدفمند می‌هراساند — ریشه واژه "assassin."'} },
          { name:{en:'Ghaznavid State (rump)',fa:'دولت غزنوی (بازمانده)'}, culture:'turkic',
            capital:{en:'Ghazni / Lahore',fa:'غزنی / لاهور'}, status:'vassal', dates:'1040–1186 AD',
            regions:['bactria','sistan'],
            desc:{en:'After Dandanaqan (1040), the Seljuks drove the Ghaznavids from Khorasan. The dynasty survived in Afghanistan and Punjab, continuing to produce Persian poetry at the Lahore court, until the Ghurids finally extinguished them in 1186.',
                  fa:'پس از دندانقان (۱۰۴۰)، سلجوقیان غزنویان را از خراسان راندند. سلسله در افغانستان و پنجاب ماند و در دربار لاهور شعر فارسی می‌سرود تا اینکه غوریان در ۱۱۸۶ آن را برانداختند.'} },
          { name:{en:'Byzantine Empire (frontier)',fa:'امپراتوری بیزانس (مرز)'}, culture:'foreign',
            capital:{en:'Constantinople',fa:'قسطنطنیه'}, status:'contested', dates:'ongoing',
            regions:['anatolia','caucasus'],
            desc:{en:'After Manzikert (1071), Anatolia rapidly fell to Seljuk penetration. By 1090 the Byzantine hold on eastern Anatolia and the Caucasus frontier was severely reduced, ceding ground to Seljuk principalities.',
                  fa:'پس از مانزیکرت (۱۰۷۱)، آناتولی به سرعت در معرض نفوذ سلجوقی قرار گرفت. تا ۱۰۹۰ کنترل بیزانس بر آناتولیای شرقی و مرز قفقاز به شدت کاهش یافته بود.'} },
        ]
      },
      {
        year:'1200 AD', yearFA:'۱۲۰۰ میلادی',
        title:{ en:'Khwarazmians & Ghurids', fa:'خوارزمشاهیان و غوریان' },
        powers:[
          { name:{en:'Khwarazmian Empire',fa:'امپراتوری خوارزمشاهی'}, culture:'turkic',
            capital:{en:'Gurganj / Samarkand',fa:'گرگانج / سمرقند'}, status:'direct', dates:'1077–1231 AD',
            regions:['transoxiana','khorasan','media','fars','azerbaijan','tabaristan'],
            desc:{en:'Rising from Seljuk vassals in Khwarazm, Ala al-Din Muhammad II expanded his empire across most of Iran and Transoxiana. He championed Persian culture but fatally provoked Genghis Khan, leading to the Mongol invasion.',
                  fa:'علاءالدین محمد خوارزمشاه که از خوارزم برخاسته بود، امپراتوری خود را بر بیشتر ایران و ماوراءالنهر گسترش داد. او حامی فرهنگ فارسی بود اما با تحریک چنگیز خان، تهاجم ویرانگر مغول را به جان خرید.'} },
          { name:{en:'Ghurid Empire',fa:'امپراتوری غوری'}, culture:'persian',
            capital:{en:'Firuzkuh / Herat / Ghazni',fa:'فیروزکوه / هرات / غزنی'}, status:'direct', dates:'1163–1215 AD',
            regions:['bactria','sistan'],
            desc:{en:'An Eastern Iranian dynasty from the mountains of Ghur. They overthrew the Ghaznavids and expanded deep into India, establishing Persian as the administrative language of the subcontinent and building the Minaret of Jam.',
                  fa:'سلسله‌ای ایرانی‌تبار از کوه‌های غور. آنان غزنویان را برانداختند و تا عمق هند پیش رفتند، زبان فارسی را زبان اداری شبه‌قاره کردند و منار جام را ساختند.'} },
          { name:{en:'Abbasid Caliphate',fa:'خلافت عباسی'}, culture:'arab',
            capital:{en:'Baghdad',fa:'بغداد'}, status:'direct', dates:'750–1258 AD',
            regions:['mesopotamia','elam'],
            desc:{en:'Under Caliph al-Nasir, the Abbasids briefly regained political and military independence in Iraq and Khuzestan, playing the Khwarazmians and Ghurids against each other before the Mongol cataclysm.',
                  fa:'در دوره خلیفه الناصر، عباسیان برای مدتی کوتاه استقلال سیاسی و نظامی خود را در عراق و خوزستان بازیافتند و پیش از طوفان مغول، خوارزمشاهیان و غوریان را به جان هم انداختند.'} },
          { name:{en:'Ismaili Nizari State (Assassins)',fa:'دولت نزاری اسماعیلی (فدائیان)'}, culture:'persian',
            capital:{en:'Alamut',fa:'الموت'}, status:'contested', dates:'1090–1256 AD',
            regions:['tabaristan'],
            desc:{en:'The network of Ismaili fortresses continued to maintain independence, resisting both Seljuk and Khwarazmian sieges until they were finally destroyed by Hulagu Khan.',
                  fa:'شبکه قلعه‌های اسماعیلی استقلال خود را حفظ کرد و در برابر محاصره‌های سلجوقی و خوارزمشاهی مقاومت کرد تا اینکه سرانجام به دست هولاکو خان نابود شد.'} }
        ]
      }
    ]
  }
];
